<#
  Cap WSL2 so a Docker build can never freeze Windows.

  WSL2 defaults to roughly half the machine's RAM and all CPU cores. On a laptop
  that is also the desktop you are sitting at, a build then starves the OS and
  the machine appears to hang. This writes a sized .wslconfig and restarts WSL.

  Run in PowerShell (no admin needed):
    powershell -ExecutionPolicy Bypass -File .\scripts\windows-tune-wsl.ps1
#>

param(
  [int]$MemoryGb    = 0,   # 0 = pick automatically from total RAM
  [int]$Processors  = 0,   # 0 = pick automatically from core count
  [switch]$NoRestart
)

$ErrorActionPreference = 'Stop'

$totalGb = [math]::Round((Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory / 1GB)
$cores   = (Get-CimInstance Win32_Processor | Measure-Object -Property NumberOfLogicalProcessors -Sum).Sum

Write-Host "This machine: ${totalGb} GB RAM, ${cores} logical processors" -ForegroundColor Cyan

if ($MemoryGb -le 0) {
  # Leave Windows at least 4 GB, and never give WSL more than half.
  $MemoryGb = [math]::Max(2, [math]::Min([math]::Floor($totalGb / 2), $totalGb - 4))
}
if ($Processors -le 0) {
  # Leave at least one core for Windows.
  $Processors = [math]::Max(1, [math]::Min([math]::Floor($cores / 2), $cores - 1))
}

$swapGb = [math]::Max(2, [math]::Min(8, $MemoryGb))

$config = @"
# Generated by scripts/windows-tune-wsl.ps1
# Keeps Windows responsive while Docker builds.
[wsl2]
memory=${MemoryGb}GB
processors=$Processors
swap=${swapGb}GB
autoMemoryReclaim=gradual
vmIdleTimeout=60000

[experimental]
sparseVhd=true
"@

$path = Join-Path $env:USERPROFILE ".wslconfig"
if (Test-Path $path) {
  Copy-Item $path "$path.backup" -Force
  Write-Host "Backed up existing config to $path.backup" -ForegroundColor Yellow
}
Set-Content -Path $path -Value $config -Encoding ASCII

Write-Host ""
Write-Host "Wrote $path" -ForegroundColor Green
Write-Host "  WSL memory limit : ${MemoryGb} GB  (Windows keeps $($totalGb - $MemoryGb) GB)"
Write-Host "  WSL processors   : $Processors      (Windows keeps $($cores - $Processors))"
Write-Host ""

if ($NoRestart) {
  Write-Host "Run 'wsl --shutdown' for this to take effect." -ForegroundColor Yellow
  exit 0
}

Write-Host "Restarting WSL so the limits apply…" -ForegroundColor Cyan
wsl --shutdown
Start-Sleep -Seconds 8
Write-Host "Done. Start Docker Desktop again, then run infra/up.sh." -ForegroundColor Green
